
services:
  r1:
    image: quay.io/frrouting/frr:10.5.4
    container_name: frr-r1
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./r1/daemons:/etc/frr/daemons
      - ./r1/frr.conf:/etc/frr/frr.conf
      - ./r1/vtysh.conf:/etc/frr/vtysh.conf
    networks:
      - net12
      - net13
    command: >-
      sh -c "/usr/lib/frr/docker-start &
             sleep 10 &&
             ping -i 5 2.2.2.2 &
             ping -i 5 3.3.3.3 &
             wait"

  r2:
    image: quay.io/frrouting/frr:10.5.4
    container_name: frr-r2
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./r2/daemons:/etc/frr/daemons
      - ./r2/frr.conf:/etc/frr/frr.conf
      - ./r2/vtysh.conf:/etc/frr/vtysh.conf
    networks:
      - net12
      - net23
    command: >-
      sh -c "/usr/lib/frr/docker-start &
             sleep 10 &&
             ping -i 5 1.1.1.1 &
             ping -i 5 3.3.3.3 &
             wait"

  r3:
    image: quay.io/frrouting/frr:10.5.4
    container_name: frr-r3
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./r3/daemons:/etc/frr/daemons
      - ./r3/frr.conf:/etc/frr/frr.conf
      - ./r3/vtysh.conf:/etc/frr/vtysh.conf
    networks:
      - net13
      - net23
    command: >-
      sh -c "/usr/lib/frr/docker-start &
             sleep 10 &&
             ping -i 5 1.1.1.1 &
             ping -i 5 1.1.1.1 &
             wait"

networks:
  net12:
    driver: bridge
  net13:
    driver: bridge
  net23:
    driver: bridge
